export const ADD_USER = "ADD_USER";
export const GET_USER = "GET_USER";
export const DELETE_USER = "DELETE_USER";
export const UPDATE_USER = "UPDATE_USER";

// HERE ALL PRODUCT SHOULD BE GET IN PRODUCT PAGE
export const GET_PRODUCT = "GET_PRODUCT";

//HERE GET A SINGLE PRODUCT OR SELECTED PRODUCT WHILE CLICK IN PRODUCT 
export const GET_SINGLE_PRODUCT = 'GET_SINGLE_PRODUCT';  

//HERE ADD ITEM AND DELETE ITEM 
export const ADD_ITEM = 'ADD_ITEM';
export const GET_ITEM = 'GET_ITEM';
export const DELETE_ITEM ='DELETE_ITEM';